export { default as QRanimate } from './QRanimate/QRanimate';
export { default as QrCode } from './QRcode/QrCode';
export { default as Btn } from './button/Btn';
export { default as Form } from './form/Form';
export { default as Input } from './input/Input';
export { default as ProtectedRoute } from './layout/ProtectedRoute';
export { default as PublicRoute } from './layout/PublicRoute';
export { default as Link } from './link/Link';
export { default as LoginGoogle } from './loginGoogle/LoginGoogle';
